# Generated by Django 2.0.1 on 2019-07-03 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '新闻'},
        ),
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 17, 18, 15, 998025), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 17, 18, 15, 998072), verbose_name='更新时间'),
        ),
    ]
