# Generated by Django 2.0.1 on 2019-07-05 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190703_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tdk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('keyword', models.CharField(max_length=128, verbose_name='关键词')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
