# Generated by Django 2.0.1 on 2019-07-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default='', max_length=128, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='标题'),
        ),
    ]
