# Generated by Django 2.0.1 on 2019-07-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190725_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
    ]
